"""
Dockerfile generator.
Produces optimized Dockerfiles based on detected stack and framework.
"""

import os
import json
from typing import Optional


class DockerfileGenerator:
    """Generates production-ready Dockerfiles for various stacks."""

    @classmethod
    def generate(
        cls,
        project_path: str,
        stack: str,
        framework: Optional[str] = None,
        entry_point: str = "",
    ) -> str:
        """Generate a Dockerfile based on the stack and framework."""
        generators = {
            "nodejs": cls._generate_nodejs,
            "python": cls._generate_python,
            "go": cls._generate_go,
            "rust": cls._generate_rust,
            "static": cls._generate_static,
        }

        generator = generators.get(stack)
        if not generator:
            return cls._generate_generic(entry_point)

        return generator(project_path, framework, entry_point)

    @classmethod
    def _generate_nodejs(
        cls, project_path: str, framework: Optional[str], entry_point: str
    ) -> str:
        """Generate Dockerfile for Node.js projects."""
        node_version = "20-alpine"
        has_yarn_lock = os.path.exists(os.path.join(project_path, "yarn.lock"))
        has_pnpm_lock = os.path.exists(os.path.join(project_path, "pnpm-lock.yaml"))

        if has_pnpm_lock:
            install_cmd = "corepack enable && pnpm install --frozen-lockfile"
        elif has_yarn_lock:
            install_cmd = "yarn install --frozen-lockfile"
        else:
            install_cmd = "npm ci --only=production"

        # Determine port
        port = "3000"
        if framework in ("express", "fastify", "koa"):
            port = "3000"
        elif framework == "nextjs":
            port = "3000"

        # Check if there's a build step
        has_build = False
        pkg_path = os.path.join(project_path, "package.json")
        if os.path.exists(pkg_path):
            try:
                with open(pkg_path, "r") as f:
                    pkg = json.load(f)
                if "build" in pkg.get("scripts", {}):
                    has_build = True
            except (json.JSONDecodeError, IOError):
                pass

        dockerfile = f"""# Auto-generated by AI DevOps Auto-Pilot
FROM node:{node_version} AS base

WORKDIR /app

# Install dependencies
COPY package*.json ./
"""
        if has_yarn_lock:
            dockerfile += "COPY yarn.lock ./\n"
        if has_pnpm_lock:
            dockerfile += "COPY pnpm-lock.yaml ./\n"

        dockerfile += f"RUN {install_cmd}\n\n"
        dockerfile += "# Copy application code\nCOPY . .\n\n"

        if has_build:
            if has_pnpm_lock:
                dockerfile += "RUN corepack enable && pnpm run build\n\n"
            elif has_yarn_lock:
                dockerfile += "RUN yarn build\n\n"
            else:
                dockerfile += "RUN npm run build\n\n"

        dockerfile += f"""# Security: run as non-root user
RUN addgroup -g 1001 appgroup && adduser -u 1001 -G appgroup -s /bin/sh -D appuser
USER appuser

EXPOSE {port}

ENV NODE_ENV=production
ENV PORT={port}

CMD {cls._format_cmd(entry_point or "npm start")}
"""
        return dockerfile

    @classmethod
    def _generate_python(
        cls, project_path: str, framework: Optional[str], entry_point: str
    ) -> str:
        """Generate Dockerfile for Python projects."""
        python_version = "3.12-slim"
        port = "8000"

        has_requirements = os.path.exists(os.path.join(project_path, "requirements.txt"))
        has_pipfile = os.path.exists(os.path.join(project_path, "Pipfile"))
        has_pyproject = os.path.exists(os.path.join(project_path, "pyproject.toml"))

        dockerfile = f"""# Auto-generated by AI DevOps Auto-Pilot
FROM python:{python_version}

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
"""
        if has_requirements:
            dockerfile += """COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -r requirements.txt

"""
        elif has_pipfile:
            dockerfile += """COPY Pipfile Pipfile.lock* ./
RUN pip install --no-cache-dir pipenv && \\
    pipenv install --system --deploy

"""
        elif has_pyproject:
            dockerfile += """COPY pyproject.toml .
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir .

"""

        dockerfile += f"""# Copy application code
COPY . .

# Security: run as non-root user
RUN useradd --create-home --shell /bin/bash appuser
USER appuser

EXPOSE {port}

ENV PYTHONUNBUFFERED=1
ENV PORT={port}

CMD {cls._format_cmd(entry_point or "python main.py")}
"""
        return dockerfile

    @classmethod
    def _generate_go(
        cls, project_path: str, framework: Optional[str], entry_point: str
    ) -> str:
        """Generate multi-stage Dockerfile for Go projects."""
        return f"""# Auto-generated by AI DevOps Auto-Pilot
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Production stage
FROM alpine:3.19

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/main .

RUN addgroup -g 1001 appgroup && adduser -u 1001 -G appgroup -s /bin/sh -D appuser
USER appuser

EXPOSE 8080

CMD ["./main"]
"""

    @classmethod
    def _generate_rust(
        cls, project_path: str, framework: Optional[str], entry_point: str
    ) -> str:
        """Generate multi-stage Dockerfile for Rust projects."""
        return f"""# Auto-generated by AI DevOps Auto-Pilot
FROM rust:1.76-slim AS builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo 'fn main() {{}}' > src/main.rs
RUN cargo build --release
RUN rm -rf src

COPY . .
RUN touch src/main.rs && cargo build --release

# Production stage
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/app .

RUN useradd --create-home --shell /bin/bash appuser
USER appuser

EXPOSE 8080

CMD ["./app"]
"""

    @classmethod
    def _generate_static(
        cls, project_path: str, framework: Optional[str], entry_point: str
    ) -> str:
        """Generate Dockerfile for static sites using Nginx."""
        return """# Auto-generated by AI DevOps Auto-Pilot
FROM nginx:alpine

COPY . /usr/share/nginx/html

RUN chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
"""

    @classmethod
    def _generate_generic(cls, entry_point: str) -> str:
        """Generate a generic Dockerfile as fallback."""
        return f"""# Auto-generated by AI DevOps Auto-Pilot
FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN useradd --create-home --shell /bin/bash appuser
USER appuser

EXPOSE 8080

CMD {cls._format_cmd(entry_point or "echo 'No entry point detected'")}
"""

    @staticmethod
    def _format_cmd(command: str) -> str:
        """Format a command string as a JSON array for CMD directive."""
        parts = command.split()
        return json.dumps(parts)
