"""
Nginx configuration generator and manager.
Dynamically creates and manages reverse proxy configurations.
"""

import os
import subprocess
import logging
from typing import Optional
from jinja2 import Template
from app.core.config import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)

NGINX_TEMPLATE = """# Auto-generated by AI DevOps Auto-Pilot
# Project: {{ project_name }}
# Subdomain: {{ subdomain }}

server {
    listen 80;
    server_name {{ subdomain }}.{{ base_domain }};

    # TODO(Production): SSL/TLS Termination
    # To enable HTTPS, uncomment the lines below and use Certbot:
    # listen 443 ssl http2;
    # ssl_certificate /etc/letsencrypt/live/{{ base_domain }}/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/{{ base_domain }}/privkey.pem;
    # if ($scheme != "https") { return 301 https://$host$request_uri; }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Proxy settings
    location / {
        proxy_pass http://127.0.0.1:{{ port }};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Buffer settings
        proxy_buffering on;
        proxy_buffer_size 16k;
        proxy_buffers 4 32k;
    }

    # Health check endpoint
    location /health {
        access_log off;
        proxy_pass http://127.0.0.1:{{ port }};
    }

    # Error pages
    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }

    # Logging
    access_log /var/log/nginx/{{ subdomain }}_access.log;
    error_log /var/log/nginx/{{ subdomain }}_error.log;
}
"""


class NginxManager:
    """Manages Nginx reverse proxy configurations for deployed projects."""

    def __init__(self):
        self.config_dir = settings.NGINX_CONFIG_DIR
        self.base_domain = settings.BASE_DOMAIN
        self.reload_cmd = settings.NGINX_RELOAD_CMD
        self._template = Template(NGINX_TEMPLATE)

    def generate_config(
        self, subdomain: str, port: int, project_name: str
    ) -> str:
        """Generate an Nginx configuration for a subdomain routing to a container port."""
        return self._template.render(
            subdomain=subdomain,
            port=port,
            project_name=project_name,
            base_domain=self.base_domain,
        )

    def write_config(self, subdomain: str, config_content: str) -> str:
        """Write the Nginx config file and return the file path."""
        os.makedirs(self.config_dir, exist_ok=True)
        config_path = os.path.join(self.config_dir, f"{subdomain}.conf")

        with open(config_path, "w") as f:
            f.write(config_content)

        logger.info(f"Wrote Nginx config to {config_path}")
        return config_path

    def remove_config(self, subdomain: str) -> bool:
        """Remove an Nginx config file for a subdomain."""
        config_path = os.path.join(self.config_dir, f"{subdomain}.conf")
        if os.path.exists(config_path):
            os.remove(config_path)
            logger.info(f"Removed Nginx config {config_path}")
            return True
        return False

    def test_config(self) -> tuple[bool, str]:
        """Test the Nginx configuration for syntax errors."""
        try:
            result = subprocess.run(
                ["nginx", "-t"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            success = result.returncode == 0
            output = result.stdout + result.stderr
            return success, output
        except subprocess.TimeoutExpired:
            return False, "Nginx config test timed out"
        except FileNotFoundError:
            return False, "Nginx binary not found"
        except Exception as e:
            return False, f"Error testing config: {str(e)}"

    def reload(self) -> tuple[bool, str]:
        """
        Safely reload Nginx:
        1. Test config first
        2. Only reload if test passes
        """
        # Test config first
        test_ok, test_output = self.test_config()
        if not test_ok:
            logger.error(f"Nginx config test failed: {test_output}")
            return False, f"Config test failed: {test_output}"

        # Reload
        try:
            result = subprocess.run(
                self.reload_cmd.split(),
                capture_output=True,
                text=True,
                timeout=10,
            )
            success = result.returncode == 0
            output = result.stdout + result.stderr
            if success:
                logger.info("Nginx reloaded successfully")
            else:
                logger.error(f"Nginx reload failed: {output}")
            return success, output
        except subprocess.TimeoutExpired:
            return False, "Nginx reload timed out"
        except Exception as e:
            return False, f"Error reloading Nginx: {str(e)}"

    def deploy_config(
        self, subdomain: str, port: int, project_name: str
    ) -> tuple[bool, str, Optional[str]]:
        """
        Full deployment flow: generate → write → test → reload.
        Returns (success, message, public_url).
        """
        config_content = self.generate_config(subdomain, port, project_name)
        config_path = self.write_config(subdomain, config_content)

        reload_ok, reload_msg = self.reload()
        if not reload_ok:
            # Rollback: remove the config that caused issues
            self.remove_config(subdomain)
            self.reload()  # Try to reload without the bad config
            return False, f"Nginx deployment failed: {reload_msg}", None

        public_url = f"http://{subdomain}.{self.base_domain}"
        return True, "Nginx configuration deployed", public_url


# Singleton instance
nginx_manager = NginxManager()
